[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "file:./dev.db"
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["src/generated/**"]
  node_bundler = "nft"
